//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHottel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DELL-PC\\SQLEXPRESS;Initial Catalog=OOP;Integrated Security=True;Pooli" +
            "ng=False")]
        public string OOPConnectionString {
            get {
                return ((string)(this["OOPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-0NCB44N;Initial Catalog=D:\\C#\\BAITAPTUAN12\\SQPTOLINQ\\SQPTOLIN" +
            "Q\\ADVENTUREWORKS2012.MDF;Integrated Security=True")]
        public string D__C__BAITAPTUAN12_SQPTOLINQ_SQPTOLINQ_ADVENTUREWORKS2012_MDFConnectionString {
            get {
                return ((string)(this["D__C__BAITAPTUAN12_SQPTOLINQ_SQPTOLINQ_ADVENTUREWORKS2012_MDFConnectionString"]));
            }
        }
    }
}
